### ISSUE TITLE
Join isn't working for me...

### ISSUE THREAD

**Issue by assadtony** [tcr/scissors#13]
I can select a page and save it without a problem, but when trying to join several pages, this is where it simply stops... Anyone has experienced anything like this while joining?

Running in OSX Captain with the newest code...

**Comment by prescottprue** [comment]
@assadtony Also running into this. I am getting errors that the pdf file is unable to be opened.

**Comment by assadtony** [comment]
@prescottprue 
I ended up doing this, and worked for me. 
*Join* is a function of the library, not of the object. So you need to call it from the actual scissors and not the instance.

Example 

`// Put all the scissor pages in a pages array
var pages = [];

var stream = scissors.join.apply(null, pages).pdfStream().pipe(fs.createWriteStream(output));
                    stream.on('finish', function() {
                      // Return and download.
                      res.download(output);
                    })`

**Comment by cboulanger** [comment]
Can this be closed? Or do you think we need a join method on the Command instance?

**Comment by cboulanger** [comment]
No further updates, closing.
