### ISSUE TITLE
Don't use console.error() please

### ISSUE THREAD

**Issue by yetzt** [tcr/scissors#2]
I really like your module, but please throw errors and don't use console.error().

**Comment by rikkertkoppes** [comment]
Fixed on this temp fork: https://github.com/theapsgroup/scissors/

**Comment by tedeh** [comment]
It would be quite easy to have this library inherit from `events.EventEmitter` and emit error events instead.

**Comment by cboulanger** [comment]
Should be fixed as @rikkertkoppes's fork has been merged. For anything left, please open a PR.
