### ISSUE TITLE
buffer() method does not exist

### ISSUE THREAD

**Issue by cboulanger** [tcr/scissors#20]
@tcr : https://github.com/tcr/scissors/blob/master/scissors.js#L207 -> this.buffer() is not a function. Do you know what this function did? It wasn't there anymore when I started working on the code.

**Comment by cboulanger** [comment]
Duh. Duplicate of #6

**Comment by tcr** [comment]
I think it used to write the pdf to an intermediary file for commands which didn't support reading from stdin well.

**Comment by tcr** [comment]
I think it used to write the pdf to an intermediary file for commands which didn't support reading from stdin well.
