### ISSUE TITLE
rasterize.js: gs encountered an error

### ISSUE THREAD

**Issue by hieuandree** [tcr/scissors#23]
I get many error:
rasterize.js: gs encountered an error:
 GPL Ghostscript 9.18: Some glyphs of the font CAAAAA+LiberationSerif-Bold requires a patented True Type interpreter.

How to fix ?

**Comment by cboulanger** [comment]
The problem is probably what the error message says and thus a problem of ghostscript with the PDF you are using.  Nothing much scissors (which is a wrapper around PDFTK and ghostscript) can do, I am afraid.
