### ISSUE TITLE
Pdf to png : Not able to process large file

### ISSUE THREAD

**Issue by sherin-mathew** [tcr/scissors#26]
I have tried pngStream() method for small pdf file(13.72 KB) and it's working fine. But when i used pdf file of size 258.45 KB, it's not working.

**Comment by cboulanger** [comment]
Hi, can you create a test case for us as explained here: https://github.com/tcr/scissors/wiki/How-to-report-issues-to-get-a-fast-response (Point 2)

**Comment by cboulanger** [comment]
Just updated the page to add a missing console command...

**Comment by cboulanger** [comment]
@sherin-mathew sorry, link in my last comment was broken, fixed now.

**Comment by sherin-mathew** [comment]
@cboulanger Okay. I will create it and let you know.

**Comment by cboulanger** [comment]
I just tried to run your code (cloned your fork to c9.io). It's not working. There are errors in the code (missing `function` in line4, `tmp is not defined` in line 9) and the code currently does nothing when called. Please fix and provide a test case that I can run and that then will show the error ... Thank you.
