### ISSUE TITLE
Length of a PDF

### ISSUE THREAD

**Issue by sjorssnoeren** [tcr/scissors#7]
Hi,

Is it possible to retrieve the length of the PDF file?

Thanks

**Comment by rikkertkoppes** [comment]
Number of pages or file length?

I am currently maintaining a fork on https://github.com/theapsgroup/scissors until tcr picks it up again

**Comment by sjorssnoeren** [comment]
Number of pages would be nice! Thanks for your effort :)

**Comment by rikkertkoppes** [comment]
That's in the works, however, I am also sporadically working on the codebase.

For now, you may be able to use something like:

    function getInfo(input,cb) {
        var cmd = [
            'pdftk',
            input,
            'dump_data'
        ];
        var prog = exec(cmd.join(' '),cb);
    }

That's the basis for my implementation anyway
